baseURL: https://lug.berlin/
title: Local User Groups · Berlin

languageCode: de-de
cleanDestinationDir: true
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true

theme: ananke

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
